### ISSUE TITLE
None of the provided bios are valid

### ISSUE THREAD

**Issue by timothymiller** [korzhyk/CLOVER-Z370-AORUS-Gaming-7#10]
I am on F13 official from the Gigabyte website. I am having troubles booting into macOS (previously was fine on F11) so I tried to flash one of the provided bios from this project. The F13 & F11 in misc are not valid zip files & cannot be extracted, nor are they recognized in Q-Flash. The mod version of F13 does extract & show up in Q-Flash, but when attempting to flash it, a warning displays "invalid bios file"

**Comment by korzhyk** [comment]
https://github.com/korzhyk/CLOVER-Z370-AORUS-Gaming-7#how-to-install-modded-bios

**Comment by timothymiller** [comment]
You can also change the file extension to .rar from .zip and unrar the file, and Q-Flash as usual.
