### ISSUE TITLE
Gigabyte z370 aorus gaming 7-OP

### ISSUE THREAD

**Issue by Simetix** [korzhyk/CLOVER-Z370-AORUS-Gaming-7#12]
Hello.
Please help me with my problem! 
I have a video card gigabyte z370 aorus gaming 7-op(http://www.gigabyte.ru/products/page/mb/z370_aorus_gaming_7-oprev_10#kf
), and I can’t flash it with your firmware gigabyte z370 aorus gaming 7 :(
That mother cards are the same , but only mine was included with Optane like a bonus. 
Please tell me how I can change BIOS ID or how I can flash my card with your firmware, because I’m not good at this :(
Please help me how do this or maybe you can change this?

**Comment by korzhyk** [comment]
Please use `Z370AOG7_F13RB.zip`. This is official version with `CFG-Lock` option provided by Gigabyte support. Flashing modded BIOS is not necessary and for advanced users.
