### ISSUE TITLE
How did you add CFG lock option to bios?

### ISSUE THREAD

**Issue by randomGuypassingby** [korzhyk/CLOVER-Z370-AORUS-Gaming-7#13]
Not an issue but I'm wondering how did you add the CFG lock option in the bios? I would like to do it for f14.

**Comment by korzhyk** [comment]
@randomGuypassingby you can request BIOS with CFG-Lock option in https://esupport.gigabyte.com/

**Comment by randomGuypassingby** [comment]
I see. Thank you! I tried requesting it but they said wouldn’t share it. :( Guess I’ll continue without it.
