### ISSUE TITLE
Gigabyte Z370 AORUS Gaming WIFI rev. 1

### ISSUE THREAD

**Issue by boesbo** [korzhyk/CLOVER-Z370-AORUS-Gaming-7#3]
I have a Gigabyte Z370 AORUS Gaming WIFI rev. 1.
It works almost everything, but I have 2 problems:
1. USB 3.0 (external hdd, modern usb) does not work
2. USB 3.1 Type C does not work (I tried to connect it as an external monitor with a Type-C HDMI cable)

Can you help me? :) thank you

____
Gigabyte Z370 AORUS Gaming WIFI (Codec audio is Creative)
Intel I7 8700K
16x2 gb Corsair 3000mhz
No External GPU

**Comment by korzhyk** [comment]
Hi!
1. It's very strange but I use an external HDD in USB3 mode. And everything is ok.
2. You can get some information about USB Type-C (connector/physical port type) and supported protocols in great article https://blog.fosketts.net/2016/10/29/total-nightmare-usb-c-thunderbolt-3/. TL;dr ASMedia3142 provide a USB3.1 Gen 2 protocol which is regular USB with higher speeds, but in you case ASMedia3142 did't support **Alternate Mode** which provide a digital video protocols such as HDMI, DP and so on. So it's ok when you can't use this USB Type-C port as HDMI.

Oh! I got it, I see you using a different mobo. So yes, you need to adjust your mobo USB ports in **Legacy_USB3.kext**

**Comment by boesbo** [comment]
Do not I also need to create ACPI Patches?
what have I seen, what do they solve?
can you give a guide to understand how to create them?

Thank you!

**Comment by korzhyk** [comment]
@boesbo there no any ACPI patches. You must use a correct DSDT table. In this file `
        CLOVER-Z370-AORUS-Gaming-7/OEM/Z370 AORUS Gaming 7/ACPI/patched/DSDT.aml
      ` I just resolve warnings and errors but you can't use this file for your system, coz there a different mobos.

To detect your USB ports, such as: https://github.com/korzhyk/CLOVER-Z370-AORUS-Gaming-7/blob/master/misc/physical-usb-ports.png you can use a patch to unlock ports limit (but put away a `Legacy_USB3.kext`). And after this you need `IORegistryExplorer` or `IOJones` to detect a your HS and SS interfaces. And you can put your mappings to table like this https://github.com/korzhyk/CLOVER-Z370-AORUS-Gaming-7#usb-ports-mapping and adjust `Legacy_USB3.kext` for your system.

**Comment by boesbo** [comment]
Thank you so much I will try and in case I will send you a commit so as to share this knowledge.

A question just out of curiosity, what warning did you solve?

**Comment by korzhyk** [comment]
@boesbo all warnings on compile using https://github.com/acidanthera/MaciASL

**Comment by boesbo** [comment]
@korzhyk  Were errors created in the DSDT.aml file autogenerated by Clover?
I hoped he did not make mistakes. You put me in doubt :(

**Comment by korzhyk** [comment]
DSDT/SSDT tables is BIOS related. Clover can dump this tables into `ACPI/origin` folder. After dumping you can use mac app **MaciASL** or console version **iasl** to compile/decompile your *DSDT*. But there a 100% chance that, during compiling compiler show to you some errors and warnings. And this problems you must resolve. And this issue is not really related to this project so you can get more info on https://www.insanelymac.com/forum/530-guides/
