### ISSUE TITLE
F12 BIOS ACPI DSDT not compatible

### ISSUE THREAD

**Issue by korzhyk** [korzhyk/CLOVER-Z370-AORUS-Gaming-7#5]
There an error when trying to load macOS.
![IMG_20190320_140627](https://user-images.githubusercontent.com/1100134/54710994-907c2500-4b51-11e9-9d92-7353f73f98ae.jpg)
Booting with DSDT from F11 (in repo) as expected.
[DSDT_F12.zip](https://github.com/korzhyk/CLOVER-Z370-AORUS-Gaming-7/files/2989663/DSDT_F12.zip)

**Comment by korzhyk** [comment]
[DSDT_F12.zip](https://github.com/korzhyk/CLOVER-Z370-AORUS-Gaming-7/files/2989662/DSDT_F12.zip)

**Comment by lucacri** [comment]
It doesn't boot at all? I was just about to install the F12 firmware..

**Comment by korzhyk** [comment]
@lucacri you can use a DSDT from F11. In F12 there are minor changes but this changes did't allow to boot system. On screenshot above, contains `ACPI Exception`.

**Comment by korzhyk** [comment]
To fix this issue I just comment out _STA method (RTC device is Always Enabled)
````
        Device (RTC)
        {
            Name (_HID, EisaId ("PNP0B00") /* AT Real-Time Clock */)  // _HID: Hardware ID
            Name (_CRS, ResourceTemplate ()  // _CRS: Current Resource Settings
            {
                IO (Decode16,
                    0x0070,             // Range Minimum
                    0x0070,             // Range Maximum
                    0x01,               // Alignment
                    0x08,               // Length
                    )
                IRQNoFlags ()
                    {8}
            })
//
// Enable RTC for macOS is important
//
//            Method (_STA, 0, NotSerialized)  // _STA: Status
//            {
//                If ((STAS == One))
//                {
//                    Return (0x0F)
//                }
//                Else
//                {
//                    Return (Zero)
//                }
//            }
        }
````
And new device `AWAC` will be always disabled because there incompatible capabilities with Apple specification https://pikeralpha.wordpress.com/2017/07/02/applesmcrtc-kext-panics/

````
    Scope (_SB)
    {
        Device (AWAC)
        {
            Name (_HID, "ACPI000E" /* Time and Alarm Device */)  // _HID: Hardware ID
...
            Method (_STA, 0, NotSerialized)  // _STA: Status
            {
		Return (Zero)
            }

            Method (_GCP, 0, NotSerialized)  // _GCP: Get Capabilities
            {
                Return (0xB7)
            }
...
````

**Comment by lucacri** [comment]
Damn great job! Does it give you any issues? I'm hesitant to move to F12......

**Comment by vodkaflip** [comment]
Agree on the great job. Not to spoil the party, but F13 is out in the meantime with an "Update iRST to improve Optane compatibility with 9th Gen R0 CPU"

**Comment by korzhyk** [comment]
@vodkaflip F13 BIOS was tested yesterday, so you can use fresh DSDT now https://github.com/korzhyk/CLOVER-Z370-AORUS-Gaming-7/releases

**Comment by vodkaflip** [comment]
awesome - works like a charm! Thanks again for the fast & excellent work!

**Comment by cattyhouse** [comment]
Hi, check here for a new method, no DSDT patch needed

https://www.tonymacx86.com/threads/guide-another-method-to-fix-kernel-panic-on-many-new-bios-asrock-gigabyte.279209/

**Comment by korzhyk** [comment]
@cattyhouse I use my DSDT because it didn't overloaded by some legacy things.
