### ISSUE TITLE
No sound from headset while jack in the back is inserted

### ISSUE THREAD

**Issue by lucacri** [korzhyk/CLOVER-Z370-AORUS-Gaming-7#6]
Again, fantastic work, @korzhyk!

I have a small bug which I have been trying to fix and I might need some brainstorming :)

So, I usually have a set of speakers attached to the back 3.5mm audio jack of the Hackintosh (with sound working perfectly). 
If I plug in a headset on the front panel audio jack, the audio still goes to the back, no matter what I do in Sound Preferences.

Any idea of why this could be happening? Is it happening to you too?

**Comment by korzhyk** [comment]
Hi @lucacri today I faced with this issue too and there are no progress. I'm tried to use last 5 releases of AppleALC but all this kexts has same behaviour. But I used only F11RB and F13RB versions of BIOS.

**Comment by korzhyk** [comment]
Fixed in https://github.com/korzhyk/CLOVER-Z370-AORUS-Gaming-7/commit/540753b4731c4a2027b44a1451c68fb6dd0c3bd2

**Comment by lucacri** [comment]
Omg you are awesome! Do I need to use the patched firmware for this? I’m scared :-)

**Comment by korzhyk** [comment]
@lucacri nope, replace layout-id https://github.com/korzhyk/CLOVER-Z370-AORUS-Gaming-7/blob/master/OEM/Z370%20AORUS%20Gaming%207/config.plist#L119
