### ISSUE TITLE
Modded Bios...

### ISSUE THREAD

**Issue by esmith1966** [korzhyk/CLOVER-Z370-AORUS-Gaming-7#8]
I have a fresh motherboard...

Confirming bios flash instructions
(I have previously only used the Gigabyte flash tools...)

This is the command to flash the bios  :   

FPT.efi --savemac -f mod_Z370AOG7.F13RB

correct?

This is to permit use of Intel Management software : FWUpdLcl64.exe -allowsv -f 11.8.60.3561.bin

correct?

What is the difference between 

1. mod_Z370AOG7.F13RB, 
2. Z370AOG7_F13RB, and 
3. Z370AOG7.F13 (downloaded from Gigabyte)?

Why do we need to permit use of Intel Management utilities?

**Comment by esmith1966** [comment]
This is the command to flash the bios  :   

FPT.efi --savemac -f mod_Z370AOG7.F13RB

correct?

This is to permit use of Intel Management software : FWUpdLcl64.exe -allowsv -f 11.8.60.3561.bin

correct?

**Comment by korzhyk** [comment]
1. Flash command is correct
2. To use latest Intel ME you need run this command after every BIOS flash (https://www.win-raid.com/t3217f44-OFFER-Gigabyte-GA-Z-Aorus-Gaming-BIOS-mod.html)
3. Modded BIOS `mod_Z370AOG7.F13RB` contains latests drivers and CPU microcodes based on `Z370AOG7_F13RB`, `Z370AOG7_F13RB` is official provided BIOS with `CFG Lock` option (no need to patch KernelPM in Clover) and `Z370AOG7.F13` original BIOS from Gigabyte website without `CFG Lock` option.

**Comment by esmith1966** [comment]
Ok 

So I will need to install windows to run this?

**Comment by korzhyk** [comment]
You need this only if you use windows.

**Comment by esmith1966** [comment]
where can I find the 11.8.60.3561.bin file...

I cannot see to locate that particular file

**Comment by esmith1966** [comment]
Flashed the motherboard and it said success...
powered off... rebooted..
motherboard did not go to post screen
it rebooted over and over until I got F7 bios...

Flashed it again.
now it just reboots over and over...

How do I get to the post screen?
How do I get into a recovery mode.

**Comment by esmith1966** [comment]
Is my motherboard dead?

**Comment by korzhyk** [comment]
Just clear CMOS.

**Comment by esmith1966** [comment]
I tried

It reboots over and over and over

I have reset bios using that button multiple times

**Comment by esmith1966** [comment]
I am getting codes while the board starts up....

Would installing a graphics card help?

**Comment by korzhyk** [comment]
@esmith1966 only one time CMOS reset is needed. If main BIOS is corrupted motherboard will use second (backup) BIOS. Did you clear CMOS referring to User's Guide recommendations?

**Comment by esmith1966** [comment]
The first time it used the backup bios 

I then flashed again

Did I flash the backup bios?

I get boot codes but no video & no post screen

**Comment by esmith1966** [comment]
Is the modded bios required to install OS X?

**Comment by korzhyk** [comment]
@esmith1966 please check README.
And answer: NO

**Comment by esmith1966** [comment]
OK... All Good...
Will probably RMA this board and use my 2nd one...
